global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'delayed-notifier'
    static_configs:
      - targets: ['delayed-notifier_main-server:7777']
    metrics_path: /metrics

  - job_name: 'shortener'
    static_configs:
      - targets: ['shortener_main-server:7779']
    metrics_path: /metrics
  
  - job_name: 'comment-tree'
    static_configs:
      - targets: ['comment-tree_main-server:7781']
    metrics_path: /metrics
  
  - job_name: 'image-processor'
    static_configs:
      - targets: ['image-processor_main-server:7783']
    metrics_path: /metrics

  - job_name: 'event-booker'
    static_configs:
      - targets: ['event-booker_main-server:7785']
    metrics_path: /metrics

  - job_name: 'sales-tracker'
    static_configs:
      - targets: ['sales-tracker_main-server:7787']
    metrics_path: /metrics

  - job_name: 'warehouse-control'
    static_configs:
      - targets: ['warehouse-control_main-server:7789']
    metrics_path: /metrics

  - job_name: 'calendar'
    static_configs:
      - targets: ['calendar_main-server:7791']
    metrics_path: /metrics

  - job_name: 'shortener-opt'
    static_configs:
      - targets: ['shortener-opt_main-server:7793']
    metrics_path: /metrics

  - job_name: 'node'
    static_configs:
      - targets: ['172.17.0.1:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
