MAKEFLAGS += --no-print-directory

NAME = Webhook

up:
	@echo "Starting ${NAME}..."
	cmd /C a.bat
	@echo "${NAME} is up and running."

# ========================
# WEBHOOK
# ========================

# WEBHOOK = webhook

# .PHONY: webhook-up

# webhook-up:
# 	$(MAKE_CMD) -C $(WEBHOOK) up